name: Release version
on:
  push:
    tags:
      - 'v*'

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract version and tag from pushed Git tag
        id: version
        run: |
          TAG_NAME="${{ github.ref_name }}"
          VERSION="${TAG_NAME#v}"
          if [[ "$VERSION" =~ - ]]; then
            TAG=$(echo "$VERSION" | awk -F '-' '{print $2}')
          else
            TAG="latest"
          fi
          if [[ "$TAG" == "latest" ]]; then
            echo "IS_PRERELEASE=false" >> $GITHUB_ENV
          else
            echo "IS_PRERELEASE=true" >> $GITHUB_ENV
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Debug extracted values
        run: |
          echo "Extracted Version: $VERSION"
          echo "Extracted Tag: $TAG"
          echo "Is Prerelease: $IS_PRERELEASE"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Update package.json version
        run: |
          jq '.version = env.VERSION' package.json > package.tmp.json && mv package.tmp.json package.json
          cat package.json

      - name: Authenticate with npm
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "NPM_TOKEN is not set"
            exit 1
          fi
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Build Project
        run: bun run build

      - name: Publish package
        run: |
          if [[ "$IS_PRERELEASE" == "true" ]]; then
            bun publish --verbose --tag $TAG
          else
            bun publish --verbose
          fi
